=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/ModifiedGENIAtypes/Modified_GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term,event,and metaknowledge annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- modified by Raheel Nawaz <nawazr@cs.man.ac.uk>  and          -->
<!-- Paul Thompson <paul.thompson@manchester.ac.uk>                -->
<!-- Date of last modification: 2 June 2011                       -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Other
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID			#REQUIRED
>

<!ELEMENT frag		(#PCDATA | term)*>
<!ATTLIST frag
		id  ID		#REQUIRED
>
<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, theme*, site*, product*, cause*, clue, comment?)>
<!ATTLIST event
		id		ID				#REQUIRED
		assertion	(exist|non-exist)		"exist"
		uncertainty 	(certain|probable|doubtful)	"certain"
		KT	(Fact|Method|Other|Investigation|Observation|Analysis)	"Observation"
		CL	(L3|L2|L1)	"L3"
		Polarity	(Positive|Negative)	 "Positive"
		Source	(Current|Other)	"Current"
		Manner	(High|Low|Neutral) "Neutral"
		LT (XXX|Propositional|Non-Propositional) "XXX"
>

<!ELEMENT type EMPTY>
<!ATTLIST type 
		class		CDATA	"UNCLASSIFIED"
>

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | corefTheme | corefSite | corefProduct | corefCause | clueExperiment | clueKT | clueCL | cluePolarity | clueSource | clueManner)*>

<!ELEMENT clueType		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT linkTheme		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT linkCause		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueTime		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueLoc		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueExperiment	(#PCDATA | clueSource | clueKT | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueKT		(#PCDATA | clueCL | cluePolarity)*>
<!ELEMENT clueCL		(#PCDATA |cluePolarity)*>
<!ELEMENT cluePolarity		(#PCDATA | clueType | linkTheme | linkCause)*>
<!ELEMENT clueSource		(#PCDATA | clueKT)*>
<!ELEMENT clueManner		(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/10064064.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=10064064" created="13/01/2007" creator="Junko Matsuura"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>10064064</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><cons id="T1" lex="(AND AML_protein Ets_protein)" sem="(AND Protein_family_or_group Protein_family_or_group)"><frag id="F1"><term id="A1" sem="Protein_molecule">AML</term></frag> and <frag id="F2"><term id="A2" sem="Protein_molecule">Ets</term></frag> <frag id="F3">proteins</frag></cons> regulate the <term id="T2" lex="I_alpha1_germ-line_promoter" sem="DNA_domain_or_region">I alpha1 germ-line promoter</term>.</sentence>
<event id="E1">
<type class="Regulation"/>
<theme idref="T2"/>
<cause idref="A1"/>
<clue>AML and Ets proteins <clueType>regulate</clueType> the I alpha1 germ-line promoter.</clue>
</event>
<event id="E2">
<type class="Regulation"/>
<theme idref="T2"/>
<cause idref="A2"/>
<clue>AML and Ets proteins <clueType>regulate</clueType> the I alpha1 germ-line promoter.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The <term id="T3" lex="_switch_recombination" sem="Other"><term id="T4" lex="immunoglobulin_heavy_chain" sem="Protein_family_or_group">immunoglobulin heavy chain</term> (<term id="T5" lex="IgH" sem="Protein_family_or_group">IgH</term>) class switch recombination</term> of <term id="T6" lex="B_lymphocyte" sem="Cell_natural">B lymphocytes</term> preferentially targets <term id="A3" sem="DNA_domain_or_region">unrearranged <term id="T7" lex="IgH_gene" sem="DNA_family_or_group">IgH genes</term></term> that have already been rendered transcriptionally active.</sentence>
<event KT="Other" id="E3">
<type class="DNA_recombination"/>
<theme idref="T5"/>
<clue>The immunoglobulin heavy chain (IgH) <clueType>class switch recombination</clueType> <clueLoc>of B lymphocytes</clueLoc> preferentially targets unrearranged IgH genes that have already been rendered transcriptionally active.</clue>
</event>
<event KT="Other" id="E4">
<type class="Positive_regulation"/>
<theme idref="A3"/>
<clue>The immunoglobulin heavy chain (IgH) class switch recombination of B lymphocytes preferentially targets unrearranged IgH genes that have already been <clueType>rendered transcriptionally active</clueType>.</clue>
</event>
<event KT="Fact" id="E105">
<type class="Positive_regulation"/>
<theme idref="E4"/>
<cause idref="E3"/>
<clue>The immunoglobulin heavy chain (IgH) class switch recombination of B lymphocytes preferentially <clueType>targets</clueType> unrearranged IgH genes that have already been rendered transcriptionally active.</clue>
</event>
<sentence id="S3">Transcription of the <term id="T9" lex="germ-line_IgH_gene" sem="DNA_family_or_group">germ-line <term id="T10" lex="IgH_gene" sem="DNA_family_or_group">IgH genes</term></term> is controlled by <term id="T11" lex="intervening_(I)_region" sem="DNA_domain_or_region">intervening (I) regions</term> upstream of their switch regions.</sentence>
<event KT="Other" id="E5">
<type class="Transcription"/>
<theme idref="T9"/>
<clue><clueType>Transcription</clueType> <linkTheme>of</linkTheme> the germ-line IgH genes is controlled by intervening (I) regions upstream of their switch regions.</clue>
</event>
<event KT="Fact" id="E6">
<type class="Regulation"/>
<theme idref="E5"/>
<cause idref="T11"/>
<clue>Transcription of the germ-line IgH genes is <clueType>controlled</clueType> <linkCause>by</linkCause> intervening (I) regions upstream of their switch regions.</clue>
</event>
<sentence id="S4">The <term id="A4" sem="DNA_domain_or_region">I alpha1 promoter</term> activates transcription of the <term id="T12" lex="human_germ-line_C_alpha1_gene" sem="DNA_domain_or_region">human germ-line C alpha1 gene</term> for <term id="T13" lex="IgA1" sem="Protein_molecule">IgA1</term> and mediates the <term id="T14" lex="transforming_growth_factor_(TGF)-beta1_responsiveness" sem="Other"><term id="T15" lex="transforming_growth_factor_(TGF)-beta1" sem="Protein_molecule">transforming growth factor (TGF)-beta1</term> responsiveness</term> of this locus.</sentence>
<event KT="Other" id="E7">
<type class="Transcription"/>
<theme idref="T12"/>
<clue>The I alpha1 promoter activates <clueType>transcription</clueType> <linkTheme>of</linkTheme> the human germ-line C alpha1 gene for IgA1 and mediates the transforming growth factor (TGF)-beta1 responsiveness of this locus.</clue>
</event>
<event KT="Fact" id="E8">
<type class="Positive_regulation"/>
<theme idref="E7"/>
<cause idref="A4"/>
<clue>The I alpha1 promoter <clueType>activates</clueType> transcription of the human germ-line C alpha1 gene for IgA1 and mediates the transforming growth factor (TGF)-beta1 responsiveness of this locus.</clue>
</event>
<event KT="Other" id="E9">
<type class="Regulation"/>
<theme idref="T11"/>
<cause idref="T15"/>
<clue>The I alpha1 promoter activates transcription of the human germ-line C alpha1 gene for IgA1 and mediates the transforming growth factor (TGF)-beta1 <clueType>responsiveness</clueType> <linkTheme>of</linkTheme> <corefTheme>this locus.</corefTheme></clue>
</event>
<event KT="Fact" id="E10">
<type class="Positive_regulation"/>
<theme idref="E9"/>
<cause idref="A4"/>
<clue>The I alpha1 promoter activates transcription of the human germ-line C alpha1 gene for IgA1 and <clueType>mediates</clueType> the transforming growth factor (TGF)-beta1 responsiveness of this locus.</clue>
</event>
<sentence id="S5">Here we show that the <term id="A7" sem="DNA_domain_or_region">I alpha1 promoter</term> contains several binding sites for the <term id="T16" lex="AML/PEBP2/CBF_family_of_transcription_factor" sem="Protein_family_or_group"><term id="T17" lex="AML" sem="Protein_family_or_group">AML</term>/PEBP2/CBF family of <term id="T18" lex="transcription_factor" sem="Protein_family_or_group">transcription factors</term></term> and that <cons id="T19" lex="(AND AML_protein Ets_protein)" sem="(AND Protein_family_or_group Protein_family_or_group)"><frag id="F4"><term id="A5" sem="Protein_molecule">AML</term></frag> and <frag id="F5"><term id="A6" sem="Protein_molecule">Ets</term></frag> <frag id="F6">proteins</frag></cons> are major regulators of the <cons id="T20" lex="(AND basal_promoter_activity TGF-beta-inducible_promoter_activity)" sem="(AND Other Other)"><frag id="F7">basal</frag> and <frag id="F8"><term id="A9" sem="Protein_molecule">TGF-beta</term>-inducible</frag> <frag id="F9">promoter activity</frag></cons>.</sentence>
<event KT="Other" id="E11">
<type class="Positive_regulation"/>
<theme idref="A7"/>
<cause idref="A9"/>
<clue>Here we show that the I alpha1 promoter contains several binding sites for the AML/PEBP2/CBF family of transcription factors and that AML and Ets proteins are major regulators of the basal and TGF-beta-<clueType>inducible</clueType> <corefTheme>promoter</corefTheme> activity.</clue>
</event>
<event KT="Other" id="E12">
<type class="Regulation"/>
<theme idref="A7"/>
<cause idref="A5"/>
<clue>Here we show that the I alpha1 promoter contains several binding sites for the AML/PEBP2/CBF family of transcription factors and that AML and Ets proteins are major <clueType>regulators</clueType> <linkTheme>of</linkTheme> the basal and TGF-beta-inducible promoter activity.</clue>
</event>
<event KT="Analysis" id="E13">
<type class="Regulation"/>
<theme idref="E11"/>
<cause idref="A5"/>
<clue>Here we <clueKT>show</clueKT> that the I alpha1 promoter contains several binding sites for the AML/PEBP2/CBF family of transcription factors and that AML and Ets proteins are major <clueType>regulators</clueType> <linkTheme>of</linkTheme> the basal and TGF-beta-inducible promoter activity.</clue>
</event>
<event KT="Other" id="E14">
<type class="Regulation"/>
<theme idref="A7"/>
<cause idref="A6"/>
<clue>Here we show that the I alpha1 promoter contains several binding sites for the AML/PEBP2/CBF family of transcription factors and that AML and Ets proteins are major <clueType>regulators</clueType> <linkTheme>of</linkTheme> the basal and TGF-beta-inducible promoter activity.</clue>
</event>
<event KT="Analysis" id="E15">
<type class="Regulation"/>
<theme idref="E11"/>
<cause idref="A6"/>
<clue>Here we <clueKT>show</clueKT> that the I alpha1 promoter contains several binding sites for the AML/PEBP2/CBF family of transcription factors and that AML and Ets proteins are major <clueType>regulators</clueType> <linkTheme>of</linkTheme> the basal and TGF-beta-inducible promoter activity.</clue>
</event>
<sentence id="S6">Our data constitute a starting point for studies to elucidate the molecular mechanism by which <term id="T21" lex="TGF-beta" sem="Protein_molecule">TGF-beta</term> regulates <term id="T22" lex="IgA_production" sem="Other"><term id="T23" lex="IgA" sem="Protein_family_or_group">IgA</term> production</term>.</sentence>
<event KT="Other" id="E16">
<type class="Gene_expression"/>
<theme idref="T23"/>
<clue>Our data constitute a starting point for studies to elucidate the molecular mechanism by which TGF-beta regulates IgA <clueType>production</clueType>.</clue>
</event>
<event KT="Fact" id="E17">
<type class="Regulation"/>
<theme idref="E16"/>
<cause idref="T21"/>
<clue>Our data constitute a starting point for studies to elucidate the molecular mechanism by which TGF-beta <clueType>regulates</clueType> IgA production.</clue>
</event>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/9858618.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9858618" created="23/11/2006" creator="Noriko Katsu"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>9858618</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Interactions between the <term id="T1" lex="class_II_transactivator" sem="Protein_molecule">class II transactivator</term> and <term id="T2" lex="CREB_binding_protein" sem="Protein_molecule">CREB binding protein</term> increase transcription of <term id="T3" lex="major_histocompatibility_complex_class_II_gene" sem="DNA_family_or_group">major histocompatibility complex class II genes</term>.</sentence>
<event id="E1">
<type class="Binding"/>
<theme idref="T1"/>
<theme idref="T2"/>
<clue><clueType>Interactions</clueType> <linkTheme>between</linkTheme> the class II transactivator and CREB binding protein increase transcription of major histocompatibility complex class II genes.</clue>
</event>
<event id="E2">
<type class="Positive_regulation"/>
<theme idref="E3"/>
<cause idref="E1"/>
<clue>Interactions between the class II transactivator and CREB binding protein <clueType>increase</clueType> transcription of major histocompatibility complex class II genes.</clue>
</event>
<event id="E3">
<type class="Transcription"/>
<theme idref="T3"/>
<clue>Interactions between the class II transactivator and CREB binding protein increase <clueType>transcription</clueType> <linkTheme>of</linkTheme> major histocompatibility complex class II genes.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term id="T4" lex="class_II_major_histocompatibility_(class_II)_gene" sem="DNA_family_or_group">Class II major histocompatibility (class II) genes</term> are regulated in a <cons id="T5" lex="(AND B-cell-specific_fashion gamma_interferon-inducible_fashion)" sem="(AND Other Other)"><frag id="F1">B-cell-specific</frag> and <frag id="F2"><term id="A1" sem="Protein_molecule">gamma interferon</term>-inducible</frag> <frag id="F3">fashion</frag></cons>.</sentence>
<event KT="Other" id="E4">
<type class="Regulation"/>
<theme idref="T4"/>
<clue>Class II major histocompatibility (class II) genes are <clueType>regulated</clueType> in a <clueLoc>B-cell</clueLoc>-specific and gamma interferon-inducible fashion.</clue>
</event>
<event KT="Fact" id="E5">
<type class="Positive_regulation"/>
<theme idref="E4"/>
<cause idref="A1"/>
<clue>Class II major histocompatibility (class II) genes are regulated in a B-cell-specific and gamma interferon-<clueType>inducible</clueType> fashion.</clue>
</event>
<sentence id="S3">The master switch for the expression of these genes is the <term id="T6" lex="class_II_transactivator" sem="Protein_molecule">class II transactivator</term> (<term id="T7" lex="CIITA" sem="Protein_molecule">CIITA</term>).</sentence>
<event KT="Fact" id="E6">
<type class="Positive_regulation"/>
<theme idref="E7"/>
<cause idref="T7"/>
<clue>The master <clueType>switch</clueType> <linkTheme>for</linkTheme> the expression of these genes is the class II transactivator (CIITA).</clue>
</event>
<event KT="Other" id="E7">
<type class="Gene_expression"/>
<theme idref="T4"/>
<clue>The master switch for the <clueType>expression</clueType> <linkTheme>of</linkTheme> <corefTheme>these genes</corefTheme> is the class II transactivator (CIITA).</clue>
</event>
<sentence id="S4">In this report, we demonstrate that one of the functions of <term id="T8" lex="CIITA" sem="Protein_molecule">CIITA</term> is to recruit the <term id="T9" lex="CREB_binding_protein" sem="Protein_molecule">CREB binding protein</term> (<term id="T10" lex="CBP" sem="Protein_molecule">CBP</term>) to <term id="T11" lex="class_II_promoter" sem="DNA_family_or_group">class II promoters</term>.</sentence>
<event KT="Other" id="E8">
<type class="Binding"/>
<theme idref="T10"/>
<theme idref="T11"/>
<clue>In this report, we demonstrate that one of the functions of CIITA is to <clueType>recruit</clueType> the CREB binding protein (CBP) <linkTheme>to</linkTheme> class II promoters.</clue>
</event>
<event KT="Analysis" id="E9">
<type class="Positive_regulation"/>
<theme idref="E8"/>
<cause idref="T8"/>
<clue><clueKT>In this report</clueKT>, we <clueKT>demonstrate</clueKT> that one of the <clueType>functions</clueType> <linkCause>of</linkCause> CIITA is to recruit the CREB binding protein (CBP) to class II promoters.</clue>
</event>
<sentence id="S5">Not only functional but also specific binding interactions between <term id="T12" lex="CIITA" sem="Protein_molecule">CIITA</term> and <term id="T13" lex="CBP" sem="Protein_molecule">CBP</term> were demonstrated.</sentence>
<event KT="Analysis" id="E10">
<type class="Correlation"/>
<theme idref="T12"/>
<theme idref="T13"/>
<clue>Not only <clueType>functional</clueType> but also specific binding <clueType>interactions</clueType> <linkTheme>between</linkTheme> CIITA and CBP were <clueKT>demonstrated</clueKT>.</clue>
</event>
<event KT="Analysis" id="E11">
<type class="Binding"/>
<theme idref="T12"/>
<theme idref="T13"/>
<clue>Not only functional but also specific <clueType>binding interactions</clueType> <linkTheme>between</linkTheme> CIITA and CBP were <clueKT>demonstrated</clueKT>.</clue>
</event>
<sentence id="S6">Moreover, a <term id="A2" sem="Protein_molecule">dominant negative form of <term id="T14" lex="CBP" sem="Protein_molecule">CBP</term></term> decreased the activity of <term id="T15" lex="class_II_promoter" sem="DNA_family_or_group">class II promoters</term> and levels of <term id="T16" lex="class_II_determinant" sem="Protein_family_or_group">class II determinants</term> on the <term id="T17" lex="surface_of_cell" sem="Cell_component">surface of cells</term>.</sentence>
<event id="E12">
<type class="Negative_regulation"/>
<theme idref="T15"/>
<cause idref="A2"/>
<clue>Moreover, a dominant negative form of CBP <clueType>decreased</clueType> the activity of class II promoters and levels of class II determinants on the surface of cells.</clue>
<comment>TPS: A2</comment></event>
<event id="E13">
<type class="Negative_regulation"/>
<theme idref="E20"/>
<cause idref="A2"/>
<clue>Moreover, a dominant negative form of CBP <clueType>decreased</clueType> the activity of class II promoters and levels of class II determinants on the surface of cells.</clue>
<comment>TPS: A2</comment></event>
<event id="E20">
<type class="Gene_expression"/>
<theme idref="T16"/>
<clue>Moreover, a dominant negative form of CBP decreased the activity of class II promoters and <clueType>levels</clueType> <linkTheme>of</linkTheme> class II determinants <clueLoc>on the surface of cells</clueLoc>.</clue>
</event>
<sentence id="S7">Finally, the inhibition of <term id="T18" lex="class_II_gene_expression" sem="Other"><term id="T19" lex="class_II_gene" sem="DNA_family_or_group">class II gene</term> expression</term> by the <term id="A3" sem="Organic_compound_other">glucocorticoid hormone</term> could be attributed to the squelching of <term id="T20" lex="CBP" sem="Protein_molecule">CBP</term> by the <term id="T21" lex="glucocorticoid_receptor" sem="Protein_family_or_group">glucocorticoid receptor</term>.</sentence>
<event KT="Other" id="E14">
<type class="Negative_regulation"/>
<theme idref="E15"/>
<cause idref="A3"/>
<clue>Finally, the <clueType>inhibition</clueType> <linkTheme>of</linkTheme> class II gene expression <linkCause>by</linkCause> the glucocorticoid hormone could be attributed to the squelching of CBP by the glucocorticoid receptor.</clue>
</event>
<event KT="Other" id="E15">
<type class="Gene_expression"/>
<theme idref="T19"/>
<clue>Finally, the inhibition of class II gene <clueType>expression</clueType> by the glucocorticoid hormone could be attributed to the squelching of CBP by the glucocorticoid receptor.</clue>
</event>
<event KT="Analysis" id="E16" uncertainty="probable">
<type class="Positive_regulation"/>
<theme idref="E14"/>
<cause idref="E17"/>
<clue>Finally, the inhibition of class II gene expression by the glucocorticoid hormone could be <clueType><clueKT>attributed</clueKT></clueType> <linkCause>to</linkCause> the squelching of CBP by the glucocorticoid receptor.</clue>
</event>
<event KT="Other" id="E17">
<type class="Negative_regulation"/>
<theme idref="T20"/>
<cause idref="T21"/>
<clue>Finally, the inhibition of class II gene expression by the glucocorticoid hormone could be attributed to the <clueType>squelching</clueType> <linkTheme>of</linkTheme> CBP <linkCause>by</linkCause> the glucocorticoid receptor.</clue>
</event>
<sentence id="S8">We conclude that <term id="T22" lex="CBP" sem="Protein_molecule">CBP</term>, a <term id="T23" lex="histone_acetyltransferase" sem="Protein_family_or_group">histone acetyltransferase</term>, plays an important role in the transcription of <term id="T24" lex="class_II_gene" sem="DNA_family_or_group">class II genes</term>.</sentence>
<event KT="Analysis" id="E18">
<type class="Regulation"/>
<theme idref="E19"/>
<cause idref="T22"/>
<clue>We <clueKT>conclude</clueKT> that CBP, a histone acetyltransferase, <clueType>plays</clueType> an important <clueType>role</clueType> <linkTheme>in</linkTheme> the transcription of class II genes.</clue>
</event>
<event KT="Other" id="E19">
<type class="Transcription"/>
<theme idref="T24"/>
<clue>We conclude that CBP, a histone acetyltransferase, plays an important role in the <clueType>transcription</clueType> <linkTheme>of</linkTheme> class II genes.</clue>
</event>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>
