=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/ModifiedGENIAtypes/Modified_GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term,event,and metaknowledge annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- modified by Raheel Nawaz <nawazr@cs.man.ac.uk>  and          -->
<!-- Paul Thompson <paul.thompson@manchester.ac.uk>                -->
<!-- Date of last modification: 2 June 2011                       -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Other
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID			#REQUIRED
>

<!ELEMENT frag		(#PCDATA | term)*>
<!ATTLIST frag
		id  ID		#REQUIRED
>
<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, theme*, site*, product*, cause*, clue, comment?)>
<!ATTLIST event
		id		ID				#REQUIRED
		assertion	(exist|non-exist)		"exist"
		uncertainty 	(certain|probable|doubtful)	"certain"
		KT	(Fact|Method|Other|Investigation|Observation|Analysis)	"Observation"
		CL	(L3|L2|L1)	"L3"
		Polarity	(Positive|Negative)	 "Positive"
		Source	(Current|Other)	"Current"
		Manner	(High|Low|Neutral) "Neutral"
		LT (XXX|Propositional|Non-Propositional) "XXX"
>

<!ELEMENT type EMPTY>
<!ATTLIST type 
		class		CDATA	"UNCLASSIFIED"
>

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | corefTheme | corefSite | corefProduct | corefCause | clueExperiment | clueKT | clueCL | cluePolarity | clueSource | clueManner)*>

<!ELEMENT clueType		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT linkTheme		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT linkCause		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueTime		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueLoc		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueExperiment	(#PCDATA | clueSource | clueKT | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueKT		(#PCDATA | clueCL | cluePolarity)*>
<!ELEMENT clueCL		(#PCDATA |cluePolarity)*>
<!ELEMENT cluePolarity		(#PCDATA | clueType | linkTheme | linkCause)*>
<!ELEMENT clueSource		(#PCDATA | clueKT)*>
<!ELEMENT clueManner		(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/7769834.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=7769834" created="04/10/2006" creator="Junko Matsuura"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>7769834</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Activation of <term id="T1" lex="pp90rsk" sem="Protein_molecule">pp90rsk</term> and <term id="T2" lex="early_growth_response-1_gene_expression" sem="Other"><term id="T3" lex="early_growth_response-1_gene" sem="DNA_domain_or_region">early growth response-1 gene</term> expression</term> by <term id="T4" lex="pokeweed_mitogen" sem="Protein_molecule">pokeweed mitogen</term> in <term id="T5" lex="human_B_cell" sem="Cell_natural">human B cells</term>.</sentence>
<event KT="Other" id="E2">
<type class="Gene_expression"/>
<theme idref="T3"/>
<clue>Activation of pp90rsk and early growth response-1 gene <clueType>expression</clueType> by pokeweed mitogen in human B cells.</clue>
</event>
<event KT="Investigation" id="E3">
<type class="Positive_regulation"/>
<theme idref="T1"/>
<cause idref="T4"/>
<clue><clueType>Activation</clueType> <linkTheme>of</linkTheme> pp90rsk and early growth response-1 gene expression <linkCause>by</linkCause> pokeweed mitogen <clueLoc>in human B cells</clueLoc>.</clue>
</event>
<event KT="Investigation" id="E4">
<type class="Positive_regulation"/>
<theme idref="E2"/>
<cause idref="T4"/>
<clue><clueType>Activation</clueType> <linkTheme>of</linkTheme> pp90rsk and early growth response-1 gene expression <linkCause>by</linkCause> pokeweed mitogen <clueLoc>in human B cells</clueLoc>.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The present studies have examined the effects of <term id="T6" lex="pokeweed_mitogen" sem="Protein_molecule">pokeweed mitogen</term> (<term id="T7" lex="PWM" sem="Protein_molecule">PWM</term>) on the induction of <term id="T8" lex="early_growth_response-1_gene" sem="DNA_domain_or_region">early growth response-1 gene</term> (<term id="T9" lex="EGR-1" sem="DNA_domain_or_region">EGR-1</term>) in <term id="T10" lex="normal_human_B_cell" sem="Cell_natural">normal <term id="T11" lex="human_B_cell" sem="Cell_natural">human B cells</term></term>.</sentence>
<event KT="Other" id="E5">
<type class="Positive_regulation"/>
<theme idref="T9"/>
<clue>The present studies have examined the effects of pokeweed mitogen (PWM) on the <clueType>induction</clueType> <linkTheme>of</linkTheme> early growth response-1 gene (EGR-1) <clueLoc>in normal human B cells</clueLoc>.</clue>
</event>
<event KT="Investigation" id="E6" uncertainty="doubtful">
<type class="Regulation"/>
<theme idref="E5"/>
<cause idref="T7"/>
<clue>The present studies have <clueKT>examined</clueKT> the <clueType>effects</clueType> <linkCause>of</linkCause> pokeweed mitogen (PWM) <linkTheme>on</linkTheme> the induction of early growth response-1 gene (EGR-1) in normal human B cells.</clue>
</event>
<sentence id="S3"><term id="T12" lex="PWM" sem="Protein_molecule">PWM</term> regulates <term id="T13" lex="EGR-1_gene_expression" sem="Other"><term id="T14" lex="EGR-1" sem="DNA_domain_or_region">EGR-1</term> gene expression</term> by both <cons id="T15" lex="(AND transcriptional_mechanism post-transcriptional_mechanism)" sem="(AND Other Other)"><frag id="F1">transcriptional</frag> and <frag id="F2">post-transcriptional</frag> <frag id="F3">mechanisms</frag></cons>.</sentence>
<event KT="Other" id="E7">
<type class="Gene_expression"/>
<theme idref="T14"/>
<clue>PWM regulates EGR-1 gene <clueType>expression</clueType> by both transcriptional and post-transcriptional mechanisms.</clue>
</event>
<event KT="Fact" id="E8">
<type class="Regulation"/>
<theme idref="E7"/>
<cause idref="T12"/>
<clue>PWM <clueType>regulates</clueType> EGR-1 gene expression by both <clueType>transcriptional and post-transcriptional</clueType> mechanisms.</clue>
</event>
<sentence id="S4"><term id="T16" lex="transient_transfection_assay" sem="Other">Transient transfection assays</term> with <term id="T17" lex="EGR-1_promoter_fragment" sem="DNA_molecule"><term id="T18" lex="EGR-1" sem="DNA_domain_or_region">EGR-1</term> promoter fragments</term> linked to the <term id="T19" lex="chloramphenicol_acetyltransferase_(CAT)_gene" sem="DNA_domain_or_region"><term id="T20" lex="chloramphenicol_acetyltransferase" sem="Protein_molecule">chloramphenicol acetyltransferase</term> (<term id="T21" lex="CAT" sem="Protein_molecule">CAT</term>) gene</term> demonstrated that <term id="T22" lex="PWM" sem="Protein_molecule">PWM</term> induced <term id="T23" lex="EGR-1_transcription" sem="Other"><term id="T24" lex="EGR-1" sem="DNA_domain_or_region">EGR-1</term> transcription</term> is conferred by the <term id="T25" lex="CArG_motif" sem="DNA_domain_or_region">CArG motif</term> <term id="A50" sem="DNA_domain_or_region">(<term id="T26" lex="C_C[AT]6GG" sem="DNA_domain_or_region">C C[AT]6GG</term>) in the <term id="T27" lex="EGR-1_promoter" sem="DNA_domain_or_region"><term id="T28" lex="EGR-1" sem="DNA_domain_or_region">EGR-1</term> promoter</term>.</term></sentence>
<event KT="Other" id="E9">
<type class="Transcription"/>
<theme idref="T24"/>
<clue>Transient transfection assays with EGR-1 promoter fragments linked to the chloramphenicol acetyltransferase (CAT) gene demonstrated that PWM induced EGR-1 <clueType>transcription</clueType> is conferred by the CArG motif (C C[AT]6GG) in the EGR-1 promoter.</clue>
</event>
<event KT="Other" id="E10">
<type class="Positive_regulation"/>
<theme idref="E9"/>
<cause idref="T22"/>
<clue>Transient transfection assays with EGR-1 promoter fragments linked to the chloramphenicol acetyltransferase (CAT) gene demonstrated that PWM <clueType>induced</clueType> EGR-1 transcription is conferred by the CArG motif (C C[AT]6GG) in the EGR-1 promoter.</clue>
</event>
<event KT="Analysis" id="E11">
<type class="Positive_regulation"/>
<theme idref="E10"/>
<cause idref="A50"/>
<clue><clueExperiment>Transient transfection assays with EGR-1 promoter fragments linked to the chloramphenicol acetyltransferase (CAT) gene</clueExperiment> <clueKT>demonstrated</clueKT> that PWM induced EGR-1 transcription is <clueType>conferred</clueType> <linkCause>by</linkCause> the CArG motif (C C[AT]6GG) in the EGR-1 promoter.</clue>
<comment>TPS: A50</comment></event>
<sentence id="S5">The results further demonstrated the activation of <term id="T29" lex="S6_kinase" sem="Protein_molecule">S6 kinase</term> (<term id="T30" lex="pp90rsk" sem="Protein_molecule">pp90rsk</term>), evidenced by <term id="T31" lex="phosphorylation" sem="Other">phosphorylation</term> of <term id="T32" lex="S6" sem="Protein_molecule">S6</term> and <term id="T33" lex="serum_response_factor_(SRF)_peptide" sem="Peptide">serum response factor (SRF) peptides</term>, in <term id="T34" lex="PWM_treated_B_cell" sem="Cell_cultured"><term id="T35" lex="PWM" sem="Protein_molecule">PWM</term> treated <term id="A1" sem="Cell_natural">B cells</term></term>.</sentence>
<event KT="Analysis" id="E12">
<type class="Positive_regulation"/>
<theme idref="T30"/>
<clue>The results further <clueKT>demonstrated</clueKT> the <clueType>activation</clueType> <linkTheme>of</linkTheme> S6 kinase (pp90rsk), <clueKT>evidenced</clueKT> by phosphorylation of S6 and serum response factor (SRF) peptides, in PWM treated B cells.</clue>
</event>
<event id="E13">
<type class="Protein_amino_acid_phosphorylation"/>
<theme idref="T32"/>
<clue>The results further demonstrated the activation of S6 kinase (pp90rsk), evidenced by <clueType>phosphorylation</clueType> <linkTheme>of</linkTheme> S6 and serum response factor (SRF) peptides, <clueLoc>in PWM treated B cells</clueLoc>.</clue>
</event>
<event id="E14">
<type class="Protein_amino_acid_phosphorylation"/>
<theme idref="T33"/>
<clue>The results further demonstrated the activation of S6 kinase (pp90rsk), evidenced by <clueType>phosphorylation</clueType> <linkTheme>of</linkTheme> S6 and serum response factor (SRF) peptides, <clueLoc>in PWM treated B cells</clueLoc>.</clue>
</event>
<event KT="Method" id="E15">
<type class="Artificial_process"/>
<theme idref="T35"/>
<theme idref="A1"/>
<clue>The results further demonstrated the activation of S6 kinase (pp90rsk), evidenced by phosphorylation of S6 and serum response factor (SRF) peptides, in PWM <clueType>treated</clueType> B cells.</clue>
</event>
<sentence id="S6">Taken together, these findings suggest that <term id="T36" lex="PWM" sem="Protein_molecule">PWM</term> is able to initiate an <term id="T37" lex="intracytoplasmic_signalling_cascade" sem="Other">intracytoplasmic signalling cascade</term> and <term id="T38" lex="EGR-1_induction" sem="Other"><term id="T39" lex="EGR-1" sem="DNA_domain_or_region">EGR-1</term> induction</term> in <term id="T40" lex="normal_human_B_cell" sem="Cell_natural">normal <term id="T41" lex="human_B_cell" sem="Cell_natural">human B cells</term></term>.</sentence>
<event CL="L2" KT="Analysis" id="E16" uncertainty="probable">
<type class="Positive_regulation"/>
<theme idref="T37"/>
<cause idref="T36"/>
<clue>Taken together, these findings <clueKT>suggest</clueKT> that PWM is <clueCL>able</clueCL> to <clueType>initiate</clueType> an intracytoplasmic signalling cascade and EGR-1 induction <clueLoc>in normal human B cells</clueLoc>.</clue>
</event>
<event KT="Other" id="E17" uncertainty="probable">
<type class="Positive_regulation"/>
<theme idref="T39"/>
<cause idref="T36"/>
<clue>Taken together, these findings suggest that PWM is able to initiate an intracytoplasmic signalling cascade and EGR-1 <clueType>induction</clueType> <clueLoc>in normal human B cells</clueLoc>.</clue>
</event>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/2122173.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=2122173" created="11/01/2007" creator="Noriko Katsu"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>2122173</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term id="T1" lex="interferon-gamma" sem="Protein_molecule">Interferon-gamma</term> and the <term id="T2" lex="sexual_dimorphism" sem="Other">sexual dimorphism</term> of <term id="T3" lex="autoimmunity" sem="Other">autoimmunity</term>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The <term id="T4" lex="sexual_difference" sem="Other">sexual difference</term> in the incidence of <term id="T5" lex="autoimmune_disease" sem="Other">autoimmune diseases</term> has remained an enigma for many years.</sentence>
<sentence id="S3">In the examination of the induction of <term id="T6" lex="autoimmunity" sem="Other">autoimmunity</term> in <term id="T7" lex="transgenic_mice" sem="Multicellular_organism_genetically_modified">transgenic mice</term>, evidence has been obtained further implicating the <term id="T8" lex="lymphokine" sem="Protein_family_or_group">lymphokine</term> <term id="T9" lex="interferon-gamma" sem="Protein_molecule">interferon-gamma</term> in the etiology of <term id="T10" lex="autoimmunity" sem="Other">autoimmunity</term>.</sentence>
<event KT="Investigation" id="E1" uncertainty="doubtful">
<type class="Positive_regulation"/>
<theme idref="T6"/>
<clue>In the <clueKT>examination</clueKT> of the <clueType>induction</clueType> <linkTheme>of</linkTheme> autoimmunity <clueLoc>in transgenic mice</clueLoc>, evidence has been obtained further implicating the lymphokine interferon-gamma in the etiology of autoimmunity.</clue>
</event>
<event KT="Analysis" id="E2">
<type class="Regulation"/>
<theme idref="T10"/>
<cause idref="T9"/>
<clue>In the examination of the induction of autoimmunity in transgenic mice, <clueKT>evidence</clueKT> has been obtained further <clueType><clueKT>implicating</clueKT></clueType> the <corefCause>lymphokine</corefCause> interferon-gamma <linkTheme>in</linkTheme> the etiology of autoimmunity.</clue>
</event>
<sentence id="S4"><term id="T11" lex="sex_steroid_regulation" sem="Other"><term id="A1" sem="Organic_compound_other">Sex steroid</term> regulation</term> of the production of this molecule, as well as other <term id="T12" lex="cytokine" sem="Protein_molecule">cytokines</term>, may help explain the gender-specific differences in the <term id="T13" lex="immune_system" sem="Body_region">immune system</term>, including <term id="T14" lex="autoimmunity" sem="Other">autoimmunity</term>.</sentence>
<event KT="Other" id="E3">
<type class="Regulation"/>
<theme idref="E4"/>
<cause idref="A1"/>
<clue>Sex steroid <clueType>regulation</clueType> <linkTheme>of</linkTheme> the production of this molecule, as well as other cytokines, may help explain the gender-specific differences in the immune system, including autoimmunity.</clue>
</event>
<event KT="Other" id="E6">
<type class="Regulation"/>
<theme idref="E5"/>
<cause idref="A1"/>
<clue>Sex steroid <clueType>regulation</clueType> <linkTheme>of</linkTheme> the production of this molecule, as well as other cytokines, may help explain the gender-specific differences in the immune system, including autoimmunity.</clue>
</event>
<event KT="Other" id="E4">
<type class="Gene_expression"/>
<theme idref="T9"/>
<clue>Sex steroid regulation of the <clueType>production</clueType> <linkTheme>of</linkTheme> <corefTheme>this molecule</corefTheme>, as well as other cytokines, may help explain the gender-specific differences in the immune system, including autoimmunity.</clue>
</event>
<event KT="Other" id="E5">
<type class="Gene_expression"/>
<theme idref="T12"/>
<clue>Sex steroid regulation of the <clueType>production</clueType> <linkTheme>of</linkTheme> this molecule, as well as other cytokines, may help explain the gender-specific differences in the immune system, including autoimmunity.</clue>
</event>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/2006423.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=2006423" created="21/03/2006" creator="Hitomi MASUDA"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>2006423</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Isolation of a <term id="T1" lex="rel-related_human_cDNA" sem="DNA_molecule">rel-related human cDNA</term> that potentially encodes the <term id="T2" lex="65-kD_subunit" sem="Protein_molecule">65-kD subunit</term> of <term id="T3" lex="NF-kappa_B" sem="Protein_molecule">NF-kappa B</term> [published erratum appears in Science 1991 Oct 4;254(5028):11]</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">A <term id="A1" sem="Polynucleotide"><term id="T4" lex="DNA_probe" sem="DNA_family_or_group">DNA probe</term> that spanned a domain conserved among the <term id="T5" lex="proto-oncogene_c-rel" sem="DNA_domain_or_region">proto-oncogene c-rel</term>, the <term id="T6" lex="Drosophila_morphogen_dorsal" sem="Protein_molecule">Drosophila morphogen dorsal</term>, and the <term id="T7" lex="p50_DNA_binding_subunit" sem="Protein_molecule"><term id="T8" lex="p50" sem="Protein_molecule">p50</term> DNA binding subunit</term> of <term id="T9" lex="NF-kappa_B" sem="Protein_molecule">NF-kappa B</term></term> was generated from <term id="T10" lex="Jurkat_T_cell_complementary_DNA" sem="DNA_family_or_group">Jurkat T cell complementary DNA</term> with the <term id="T11" lex="polymerase_chain_reaction" sem="Other">polymerase chain reaction</term> (<term id="T12" lex="PCR" sem="Other">PCR</term>) and <term id="T13" lex="degenerate_oligonucleotide" sem="Polynucleotide">degenerate oligonucleotides</term>.</sentence>
<sentence id="S3">This probe was used to identify a <term id="T14" lex="rel-related_complementary_DNA" sem="DNA_molecule">rel-related complementary DNA</term> that hybridized to a <term id="T15" lex="2.6-kilobase_messenger_RNA" sem="RNA_molecule">2.6-kilobase messenger RNA</term> present in <cons id="T16" lex="(AND human_T_lymphocyte human_B_lymphocyte)" sem="(AND Cell_natural Cell_natural)"><frag id="F1">human</frag> <frag id="F2">T</frag> and <frag id="F3">B</frag> <frag id="F4">lymphocytes</frag></cons>.</sentence>
<event id="E2">
<type class="Binding"/>
<theme idref="T14"/>
<theme idref="T15"/>
<clue>This probe was used to identify a rel-related complementary DNA that <clueType>hybridized</clueType> <linkTheme>to</linkTheme> a 2.6-kilobase messenger RNA present <clueLoc>in human T</clueLoc> and B <clueLoc>lymphocytes</clueLoc>.</clue>
</event>
<event id="E102">
<type class="Binding"/>
<theme idref="T14"/>
<theme idref="T15"/>
<clue>This probe was used to identify a rel-related complementary DNA that <clueType>hybridized</clueType> <linkTheme>to</linkTheme> a 2.6-kilobase messenger RNA present <clueLoc>in human</clueLoc> T and <clueLoc>B lymphocytes</clueLoc>.</clue>
</event>
<event LT="Propositional" id="E3">
<type class="Binding"/>
<theme idref="T14"/>
<theme idref="A1"/>
<clue><corefTheme>This probe</corefTheme> was used to <clueType>identify</clueType> a rel-related complementary DNA that hybridized to a 2.6-kilobase messenger RNA present in human T and B lymphocytes.</clue>
<comment>TPS: A1</comment></event>
<sentence id="S4">In vitro <term id="T17" lex="transcription" sem="Other">transcription</term> and <term id="T18" lex="translation" sem="Other">translation</term> of the <term id="T19" lex="complementary_DNA" sem="DNA_molecule">complementary DNA</term> resulted in the synthesis of a protein with an apparent molecular size of <term id="T20" lex="65_kilodalton" sem="Protein_molecule">65 kilodaltons</term> (kD).</sentence>
<event id="E4">
<type class="Transcription"/>
<theme idref="T19"/>
<clue>In vitro <clueType>transcription</clueType> and translation <linkTheme>of</linkTheme> the complementary DNA resulted in the synthesis of a protein with an apparent molecular size of 65 kilodaltons (kD).</clue>
</event>
<event id="E5">
<type class="Translation"/>
<theme idref="T19"/>
<clue>In vitro transcription and <clueType>translation</clueType> <linkTheme>of</linkTheme> the complementary DNA resulted in the synthesis of a protein with an apparent molecular size of 65 kilodaltons (kD).</clue>
</event>
<event id="E6">
<type class="Gene_expression"/>
<theme idref="T20"/>
<clue>In vitro transcription and translation of the complementary DNA resulted in the <clueType>synthesis</clueType> <linkTheme>of</linkTheme> a protein with an apparent molecular size of 65 kilodaltons (kD).</clue>
</event>
<event LT="Propositional" id="E100">
<type class="Positive_regulation"/>
<theme idref="E6"/>
<cause idref="E4"/>
<cause idref="E5"/>
<clue>In vitro transcription and translation of the complementary DNA <clueType>resulted</clueType> <linkTheme>in</linkTheme> the synthesis of a protein with an apparent molecular size of 65 kilodaltons (kD).</clue>
</event>
<sentence id="S5">The translated protein showed weak <term id="T21" lex="DNA_binding" sem="Other">DNA binding</term> with a specificity for the <term id="T22" lex="kappa_B_binding_motif" sem="DNA_substructure">kappa B binding motif</term>.</sentence>
<event LT="Propositional" Manner="Low" id="E7">
<type class="Binding"/>
<theme idref="T22"/>
<theme idref="T20"/>
<clue><corefTheme idref1="T20">The translated protein</corefTheme> <linkTheme>showed</linkTheme> <clueManner>weak</clueManner> <corefTheme idref1="T22">DNA</corefTheme> <clueType>binding</clueType> <linkTheme>with</linkTheme> a specificity for the kappa B binding motif.</clue>
</event>
<sentence id="S6">This <term id="T23" lex="protein-DNA_complex" sem="Protein_complex">protein-DNA complex</term> comigrated with the complex obtained with the <term id="T24" lex="purified_human_p65_NF-kappa_B_subunit" sem="Protein_molecule">purified human p65 NF-kappa B subunit</term> and binding was inhibited by <term id="T25" lex="I_kappa_B-alpha" sem="Protein_molecule">I kappa B-alpha</term> and <term id="T26" lex="I_kappa-beta_protein" sem="Protein_molecule">-beta <term id="A2" sem="Protein_molecule">proteins</term></term>.</sentence>
<event LT="Propositional" id="E8">
<type class="Negative_regulation"/>
<theme idref="E7"/>
<cause idref="T25" idref1="A2"/>
<clue>This protein-DNA complex comigrated with the complex obtained with the purified human p65 NF-kappa B subunit and <corefTheme>binding</corefTheme> was <clueType>inhibited</clueType> <linkCause>by</linkCause> I kappa B-alpha and -beta proteins.</clue>
</event>
<event LT="Propositional" id="E9">
<type class="Negative_regulation"/>
<theme idref="E7"/>
<cause idref="T26"/>
<clue>This protein-DNA complex comigrated with the complex obtained with the purified human p65 NF-kappa B subunit and <corefTheme>binding</corefTheme> was <clueType>inhibited</clueType> <linkCause>by</linkCause> I kappa B-alpha and -beta proteins.</clue>
<comment>NER:T26 mod</comment></event>
<sentence id="S7">In addition, the <term id="T27" lex="65-kD_protein" sem="Protein_molecule">65-kD protein</term> associated with the <term id="T28" lex="p50_subunit" sem="Protein_molecule"><term id="T29" lex="p50" sem="Protein_molecule">p50</term> subunit</term> of <term id="T30" lex="NF-kappa_B" sem="Protein_molecule">NF-kappa B</term> and the <term id="T31" lex="kappa_B_probe" sem="DNA_molecule">kappa B probe</term> to form a complex with the same electrophoretic mobility as the <term id="T32" lex="NF-kappa_B-DNA_complex" sem="Protein_complex"><term id="T33" lex="NF-kappa_B" sem="Protein_molecule">NF-kappa B</term>-DNA complex</term>.</sentence>
<event LT="Propositional" id="E10">
<type class="Binding"/>
<theme idref="T27"/>
<theme idref="T28"/>
<theme idref="T31"/>
<clue>In addition, the 65-kD protein <clueType>associated</clueType> <linkTheme>with</linkTheme> the p50 subunit of NF-kappa B and the kappa B probe to form a complex with the same electrophoretic mobility as the NF-kappa B-DNA complex.</clue>
</event>
<sentence id="S8">Therefore the <term id="T34" lex="rel-related_65-kD_protein" sem="Protein_molecule">rel-related 65-kD protein</term> may represent the <term id="T35" lex="p65_subunit" sem="Protein_molecule">p65 subunit</term> of the <term id="T36" lex="active_NF-kappa_B_transcription_factor_complex" sem="Protein_complex">active NF-kappa B transcription factor complex</term>.</sentence>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>
