=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/ModifiedGENIAtypes/Modified_GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term,event,and metaknowledge annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- modified by Raheel Nawaz <nawazr@cs.man.ac.uk>  and          -->
<!-- Paul Thompson <paul.thompson@manchester.ac.uk>                -->
<!-- Date of last modification: 2 June 2011                       -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Other
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID			#REQUIRED
>

<!ELEMENT frag		(#PCDATA | term)*>
<!ATTLIST frag
		id  ID		#REQUIRED
>
<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, theme*, site*, product*, cause*, clue, comment?)>
<!ATTLIST event
		id		ID				#REQUIRED
		assertion	(exist|non-exist)		"exist"
		uncertainty 	(certain|probable|doubtful)	"certain"
		KT	(Fact|Method|Other|Investigation|Observation|Analysis)	"Observation"
		CL	(L3|L2|L1)	"L3"
		Polarity	(Positive|Negative)	 "Positive"
		Source	(Current|Other)	"Current"
		Manner	(High|Low|Neutral) "Neutral"
		LT (XXX|Propositional|Non-Propositional) "XXX"
>

<!ELEMENT type EMPTY>
<!ATTLIST type 
		class		CDATA	"UNCLASSIFIED"
>

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | corefTheme | corefSite | corefProduct | corefCause | clueExperiment | clueKT | clueCL | cluePolarity | clueSource | clueManner)*>

<!ELEMENT clueType		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT linkTheme		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT linkCause		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueTime		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueLoc		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueExperiment	(#PCDATA | clueSource | clueKT | cluePolarity | clueManner | clueCL)*>
<!ELEMENT clueKT		(#PCDATA | clueCL | cluePolarity)*>
<!ELEMENT clueCL		(#PCDATA |cluePolarity)*>
<!ELEMENT cluePolarity		(#PCDATA | clueType | linkTheme | linkCause)*>
<!ELEMENT clueSource		(#PCDATA | clueKT)*>
<!ELEMENT clueManner		(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA | clueKT | clueSource | cluePolarity | clueManner | clueCL)*>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/9047239.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9047239" created="07/02/22" creator="Yumiko Katsu"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>9047239</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">A <term id="A101" sem="DNA_domain_or_region"><term id="T1" lex="T_cell-specific_enhancer" sem="DNA_domain_or_region">T cell-specific enhancer</term> in the <term id="T2" lex="interleukin-3_locus" sem="DNA_domain_or_region">interleukin-3 locus</term></term> is activated cooperatively by <cons id="T3" lex="(AND Oct_element NFAT_element)" sem="(AND DNA_domain_or_region DNA_domain_or_region)"><frag id="F1"><term id="A2" sem="DNA_domain_or_region">Oct</term></frag> and <frag id="F2"><term id="A3" sem="DNA_domain_or_region">NFAT</term></frag> <frag id="F3"><term id="A4" sem="DNA_domain_or_region">elements</term></frag></cons> <term id="A102" sem="DNA_domain_or_region">within a <term id="T4" lex="DNase_I-hypersensitive_site" sem="DNA_domain_or_region">DNase I-hypersensitive site</term></term>.</sentence>
<event id="E1">
<type class="Positive_regulation"/>
<theme idref="A101"/>
<cause idref="A2" idref1="A4" idref2="A102"/>
<cause idref="A3" idref1="A4" idref2="A102"/>
<clue>A T cell-specific enhancer in the interleukin-3 locus is <clueType>activated cooperatively</clueType> <linkCause>by</linkCause> Oct and NFAT elements within a DNase I-hypersensitive site.</clue>
<comment>TPS A101, TPS A102</comment></event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term id="T5" lex="interleukin-3" sem="Protein_molecule">Interleukin-3</term> (<term id="T6" lex="IL-3" sem="Protein_molecule">IL-3</term>) is a <term id="T7" lex="cytokine" sem="Protein_family_or_group">cytokine</term> that is expressed primarily in <term id="T8" lex="activated_T_cell" sem="Cell_natural">activated <term id="A1" sem="Cell_natural">T cells</term></term>.</sentence>
<event KT="Fact" id="E3">
<type class="Gene_expression"/>
<theme idref="T6"/>
<clue>Interleukin-3 (IL-3) is a cytokine that is <clueType>expressed</clueType> primarily <clueLoc>in activated T cells</clueLoc>.</clue>
</event>
<event KT="Other" id="E4">
<type class="Physiological_process"/>
<theme idref="A1"/>
<clue>Interleukin-3 (IL-3) is a cytokine that is expressed primarily in <clueType>activated</clueType> T cells.</clue>
</event>
<sentence id="S3">Here we identified an inducible <term id="T9" lex="T_cell-specific_enhancer" sem="DNA_domain_or_region">T cell-specific enhancer</term> 14 kb upstream of the <term id="T10" lex="IL-3_gene" sem="DNA_domain_or_region"><term id="T11" lex="IL-3" sem="Protein_molecule">IL-3</term> gene</term> that responded to activation of <term id="T12" lex="T_cell_receptor_signaling_pathway" sem="Other"><term id="T13" lex="T_cell_receptor" sem="Protein_family_or_group">T cell receptor</term> signaling pathways</term>.</sentence>
<event KT="Analysis" id="E5">
<type class="Positive_regulation"/>
<theme idref="T10"/>
<clue>Here we <clueKT>identified</clueKT> an <clueType>inducible</clueType> <clueLoc>T cell</clueLoc>-specific enhancer 14 kb upstream of the IL-3 gene that responded to activation of T cell receptor signaling pathways.</clue>
</event>
<event KT="Other" id="E6">
<type class="Positive_regulation"/>
<theme idref="T12"/>
<clue>Here we identified an inducible T cell-specific enhancer 14 kb upstream of the IL-3 gene that responded to <clueType>activation</clueType> <linkTheme>of</linkTheme> T cell receptor signaling pathways.</clue>
</event>
<event KT="Other" id="E7">
<type class="Correlation"/>
<theme idref="T10"/>
<theme idref="E6"/>
<clue>Here we identified an inducible T cell-specific enhancer 14 kb upstream of the IL-3 gene that <clueType>responded</clueType> <linkTheme>to</linkTheme> activation of T cell receptor signaling pathways.</clue>
</event>
<sentence id="S4">The <term id="A8" sem="DNA_domain_or_region"><term id="T14" lex="IL-3" sem="Protein_molecule">IL-3</term> enhancer</term> spanned an inducible <term id="T15" lex="cyclosporin_A-sensitive_DNase_I-hypersensitive_site" sem="DNA_domain_or_region"><term id="T16" lex="cyclosporin_A" sem="Organic_compound_other">cyclosporin A</term>-sensitive <term id="T17" lex="DNase_I-hypersensitive_site" sem="DNA_domain_or_region">DNase I-hypersensitive site</term></term> found only in <term id="T18" lex="T_cell" sem="Cell_natural">T cells</term>.</sentence>
<event id="E8">
<type class="Correlation"/>
<theme idref="T16"/>
<theme idref="T17"/>
<clue>The IL-3 enhancer spanned an inducible cyclosporin A-<clueType>sensitive</clueType> DNase I-hypersensitive site found only <clueLoc>in T cells</clueLoc>.</clue>
<comment>SENSITIVITY</comment></event>
<event id="E9">
<type class="Positive_regulation"/>
<theme idref="E8"/>
<clue>The IL-3 enhancer spanned an <clueType>inducible</clueType> cyclosporin A-sensitive DNase I-hypersensitive site found only <clueLoc>in T cells</clueLoc>.</clue>
</event>
<sentence id="S5">Four <term id="T19" lex="NFAT-like_element" sem="DNA_family_or_group">NFAT-like elements</term> exist within the enhancer.</sentence>
<sentence id="S6">The two most active <term id="T20" lex="NFAT-like_element" sem="DNA_family_or_group">NFAT-like elements</term> were located at the center of the <term id="T21" lex="DNase_I-hypersensitive_site" sem="DNA_domain_or_region">DNase I-hypersensitive site</term>.</sentence>
<event KT="Analysis" Manner="High" id="E10">
<type class="Positive_regulation"/>
<theme idref="T20"/>
<clue>The two <clueManner>most</clueManner> <clueType>active</clueType> NFAT-like elements were <clueKT>located</clueKT> at the center of the DNase I-hypersensitive site.</clue>
</event>
<sentence id="S7">One of these <term id="T22" lex="NFAT-like_element" sem="DNA_family_or_group">NFAT-like elements</term> encompassed overlapping <cons id="T23" lex="(AND Oct-binding_site NFATp/c-binding_site)" sem="(AND DNA_domain_or_region DNA_domain_or_region)"><frag id="F4"><term id="A5" sem="DNA_domain_or_region">Oct-</term></frag> and <frag id="F5"><term id="A6" sem="DNA_domain_or_region">NFATp/c-</term></frag><frag id="F6"><term id="A7" sem="DNA_domain_or_region">binding sites</term></frag></cons>, which functioned in a highly synergistic manner.</sentence>
<event Manner="High" id="E11">
<type class="Regulation"/>
<cause idref="A5" idref1="A7"/>
<cause idref="A6" idref1="A7"/>
<clue>One of these NFAT-like elements encompassed overlapping Oct- and NFATp/c-binding sites, which <clueType>functioned</clueType> in a <clueManner>highly</clueManner> <clueType>synergistic</clueType> manner.</clue>
<comment>NO THEME</comment></event>
<sentence id="S8">We suggest that the <term id="T24" lex="T_cell-specific_expression" sem="Other">T cell-specific expression</term> of the <term id="T25" lex="IL-3_gene" sem="DNA_domain_or_region"><term id="T26" lex="IL-3" sem="Protein_molecule">IL-3</term> gene</term> is partly controlled through the enhancer by cooperation between <cons id="T27" lex="(AND Oct_family_protein NFAT_family_protein)" sem="(AND Protein_family_or_group Protein_family_or_group)"><frag id="F7"><term id="A9" sem="Protein_family_or_group">Oct</term></frag> and <frag id="F8"><term id="A10" sem="Protein_family_or_group">NFAT</term></frag> <frag id="F9"><term id="A11" sem="Protein_family_or_group">family proteins</term></frag></cons>.</sentence>
<event KT="Other" id="E12" uncertainty="probable">
<type class="Gene_expression"/>
<theme idref="T25"/>
<clue>We suggest that the <clueLoc>T cell</clueLoc>-specific <clueType>expression</clueType> <linkTheme>of</linkTheme> the IL-3 gene is partly controlled through the enhancer by cooperation between Oct and NFAT family proteins.</clue>
</event>
<event KT="Other" id="E13" uncertainty="probable">
<type class="Regulation"/>
<theme idref="E12"/>
<cause idref="A9" idref1="A11"/>
<cause idref="A10" idref1="A11"/>
<clue>We suggest that the T cell-specific expression of the IL-3 gene is partly <clueType>controlled</clueType> through the enhancer <linkCause>by cooperation between</linkCause> Oct and NFAT family proteins.</clue>
</event>
<event CL="L2" KT="Analysis" id="E14" uncertainty="probable">
<type class="Regulation"/>
<theme idref="E13"/>
<cause idref="A8"/>
<clue>We <clueKT><clueCL>suggest</clueCL></clueKT> that the T cell-specific expression of the IL-3 gene is partly controlled <linkCause>through</linkCause> <corefCause>the enhancer</corefCause> by cooperation between Oct and NFAT family proteins.</clue>
<comment>NO CLUETYPE</comment></event>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== kermitt2/hypothesis_detection/dataset/external/Meta-knowledge_GENIA_Corpus/Corpus/1531412.xml
<?xml version='1.0'?><!DOCTYPE Annotation PUBLIC "//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN_Modified" "../ModifiedGENIAtypes/Modified_GENIA_event_20.dtd"><Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=1531412" created="13/11/2006" creator="Noriko Katsu"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>1531412</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term id="T1" lex="transcriptional_regulation" sem="Other">Transcriptional regulation</term> during <term id="T2" lex="T-cell_development" sem="Other"><term id="T3" lex="T-cell" sem="Cell_natural">T-cell</term> development</term>: the <term id="T4" lex="alpha_TCR_gene" sem="DNA_domain_or_region">alpha TCR gene</term> as a <term id="T5" lex="molecular_model" sem="Other">molecular model</term>.</sentence>
<event KT="Other" id="E1">
<type class="Regulation"/>
<theme idref="E4"/>
<clue>Transcriptional <clueType>regulation</clueType> during T-cell development: the alpha TCR gene as a molecular model.</clue>
</event>
<event KT="Investigation" id="E2">
<type class="Correlation"/>
<theme idref="E1"/>
<theme idref="E3"/>
<clue>Transcriptional regulation <linkTheme>during</linkTheme> T-cell development: the alpha TCR gene as a molecular model.</clue>
</event>
<event KT="Other" id="E3">
<type class="Cell_differentiation"/>
<theme idref="T3"/>
<clue>Transcriptional regulation during T-cell <clueType>development</clueType>: the alpha TCR gene as a molecular model.</clue>
</event>
<event KT="Other" id="E4">
<type class="Transcription"/>
<theme idref="T4"/>
<clue><clueType>Transcriptional</clueType> regulation during T-cell development: the alpha TCR gene as a molecular model.</clue>
<comment>CAUTION: THEME from the context</comment></event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The regulation of <term id="T6" lex="gene_expression" sem="Other">gene expression</term> during <term id="T7" lex="lymphocyte_differentiation" sem="Other"><term id="T8" lex="lymphocyte" sem="Cell_natural">lymphocyte</term> differentiation</term> is a complex process involving interactions between <cons id="T9" lex="(AND multiple_positive_transcriptional_regulatory_element multiple_negative_transcriptional_regulatory_element)" sem="(AND DNA_domain_or_region DNA_domain_or_region)"><frag id="F1">multiple</frag> <frag id="F2">positive</frag> and <frag id="F3">negative</frag> <frag id="F4">transcriptional regulatory elements</frag></cons>.</sentence>
<event KT="Other" id="E6">
<type class="Regulation"/>
<theme idref="T6"/>
<cause idref="E10"/>
<clue>The <clueType>regulation</clueType> <linkTheme>of</linkTheme> gene expression <clueTime>during lymphocyte differentiation</clueTime> is a complex process <linkCause>involving</linkCause> interactions between multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<event KT="Other" id="E8">
<type class="Cell_differentiation"/>
<theme idref="T8"/>
<clue>The regulation of gene expression during lymphocyte <clueType>differentiation</clueType> is a complex process involving interactions between multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<event KT="Fact" id="E9">
<type class="Regulation"/>
<theme idref="E6"/>
<cause idref="E10"/>
<clue>The regulation of gene expression during lymphocyte differentiation is a complex process <clueType>involving</clueType> interactions between multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<event KT="Other" id="E10">
<type class="Correlation"/>
<theme idref="F2" idref1="F4"/>
<theme idref="F3" idref1="F4"/>
<clue>The regulation of gene expression during lymphocyte differentiation is a complex process involving <clueType>interactions</clueType> <linkTheme>between</linkTheme> multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<sentence id="S3">In this article, <term id="T10" lex="transcriptional_regulation" sem="Other">transcriptional regulation</term> of the <term id="T11" lex="archetypal_T-cell-specific_gene" sem="DNA_domain_or_region">archetypal <term id="T12" lex="T-cell" sem="Cell_natural">T-cell</term>-specific gene</term>, <term id="T13" lex="alpha_TCR" sem="DNA_domain_or_region">alpha TCR</term>, is discussed.</sentence>
<event KT="Investigation" id="E13">
<type class="Regulation"/>
<theme idref="T13"/>
<clue>In this article, <clueType>transcriptional regulation</clueType> <linkTheme>of</linkTheme> the archetypal T-cell-specific gene, alpha TCR, is <clueKT>discussed</clueKT>.</clue>
</event>
<sentence id="S4">Major recent developments, including the identification of novel families of <term id="T14" lex="transcription_factor" sem="Protein_family_or_group">transcription factors</term> that regulate multiple <term id="T15" lex="T-cell_gene" sem="DNA_family_or_group"><term id="T16" lex="T-cell" sem="Cell_natural">T-cell</term> genes</term> during <term id="T17" lex="thymocyte_ontogeny" sem="Other">thymocyte ontogeny</term> and <term id="T18" lex="T-cell_activation" sem="Other"><term id="T19" lex="T-cell" sem="Cell_natural">T-cell</term> activation</term>, are described.</sentence>
<event KT="Analysis" id="E15">
<type class="Regulation"/>
<theme idref="T15"/>
<cause idref="T14"/>
<clue>Major recent developments, including the <clueKT>identification</clueKT> of novel families of transcription factors that <clueType>regulate</clueType> multiple <clueLoc>T-cell</clueLoc> genes during thymocyte ontogeny and T-cell activation, are described.</clue>
<comment>NER: T14 sem mod, DNA_domain_or_region -&gt; Protein_family_or_group</comment></event>
<event KT="Analysis" id="E16">
<type class="Correlation"/>
<theme idref="E15"/>
<theme idref="T17"/>
<clue>Major recent developments, including the identification of novel families of transcription factors that regulate multiple T-cell genes <linkTheme>during</linkTheme> thymocyte ontogeny and T-cell activation, are <clueKT>described</clueKT>.</clue>
</event>
<event KT="Analysis" id="E17">
<type class="Correlation"/>
<theme idref="E15"/>
<theme idref="E18"/>
<clue>Major recent developments, including the identification of novel families of transcription factors that regulate multiple T-cell genes <linkTheme>during</linkTheme> thymocyte ontogeny and T-cell activation, are <clueKT>described</clueKT>.</clue>
</event>
<event KT="Other" id="E18">
<type class="Physiological_process"/>
<theme idref="T19"/>
<clue>Major recent developments, including the identification of novel families of transcription factors that regulate multiple T-cell genes during thymocyte ontogeny and T-cell <clueType>activation</clueType>, are described.</clue>
</event>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>
